cors:
  originPatterns: http://localhost:8080,https://empresa.com.br
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-cl2q9khnovjs73b63ah0-a:5432/rest_with_spring_boot
    username: rest_with_spring_boot_user
    password: yKAiyvYESYMpT1d7dUotaHBGr5AQSa8U
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
    show-sql: false
springdoc:
  pathsToMatch: /api/**/v1/**
  swagger-ui:
    use-root-path: true