server:
  port: 8888
cors:
  originPatterns: http://localhost:8080,https://empresa.com.br
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
    show-sql: false
springdoc:
  pathsToMatch: /api/**/v1/**
  swagger-ui:
    use-root-path: true