cors:
  originPatterns: http://localhost:3000,http://localhost:8080,https://erudio.com.br
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-cl2q9khnovjs73b63ah0-a:5432/rest_with_spring_boot
    username: rest_with_spring_boot_user
    password: yKAiyvYESYMpT1d7dUotaHBGr5AQSa8U
    #url: jdbc:postgresql://localhost:5432/rest_with_spring_boot
    #username: postgres
    #password: admin123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
    show-sql: false
springdoc:
  pathsToMatch:
    - /auth/**
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true