cors:
  originPatterns: http://localhost:8080,https://empresa.com.br
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rest_with_spring_boot
    username: postgres
    password: admin123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
    show-sql: false
springdoc:
  pathsToMatch: /api/**/v1/**
  swagger-ui:
    use-root-path: true